### PR TITLE
Add illustration-1 to LoI

### PR DESCRIPTION
**Pull request by apasel422**

### CODE REVIEW

**Comment by erinendrei** [comment]
@acabal Just a note that I intentionally didn't add illustration 1 to the LoI due to 7.9.3: "illustrative musical scores" occur in the list of "Examples of illustration that might _not_ belong in an LoI". Up to you of course but unlike the two other musical figures I don't see it as an "image that a reader may wish to return to during reading".

**Comment by acabal** [comment]
But how does that differ from any of the other scores in the LoI? Maybe we should just remove the LoI entirely, since it's all just scores that follow printed text.

**Comment by erinendrei** [comment]
I figured that readers might want to return to the ballad scores, because it’s a strange/substantial choice to highlight that song, but probably not want to return to the Gloria. Maybe I’m misinterpreting the SEMoS criterion but it seems to me opinions are likely to differ about whether it’s met in certain cases.

If all three in this book should be seen as similarly illustrative I think it would make sense to cut the LoI. I actually wasn’t sure at the time whether it was needed—should have raised it in notes for the review.

**Comment by acabal** [comment]
OK, I'll just cut the LoI entirely then.

**Pull request merged**
