### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by erinendrei**
I had a thought about the currency notation yesterday and when I checked it found some minor issues. Sorry—but on the bright side these aren't things that are likely to disrupt readers. Chapter 17 is one of the densest for semantics, so I've taken some time to go over it again, believe it's OK now and don't anticipate making further PRs.

- Tag abbreviations in Ch. 17: several occurrences of “in” for inch, one occurrence of monetary “d”, two occurrences of “Co” missed due to their preceding respectively a comma and an apostrophe.

- Add no-break spaces before inch abbreviations in Ch. 17: what typogrify does here.

- [Editorial] Remove space before monetary abbreviation in Ch. 17 (1927): already removed all such spaces I could find in a single earlier commit ([a7cb5f](https://github.com/standardebooks/james-joyce_ulysses/commit/a7cb58f2ea5792f0d0ef00d531d3cdfe58f43cfa)); my earlier regexes didn't catch what needed changing here (6 d. -> 6d.). I've now searched for numerals followed by spaces followed by d or s and there's nothing else.

- Revert conversion of currency notation to fractions by typogrify: when first typogrifying I didn’t understand what was currency notation and what was a genuine fraction; realised it was an issue only when reading chapter 18 and made the required reversions in that chapter; but wasn’t aware of the fraction slash character so before the ebook's release only searched the rest of the book fruitlessly for the solidus.

- Tag list of books in stage direction in Ch. 15: not double-italicised in scans, so here given `<span>` with book epub:type. That makes lint care about titlecasing, so an exception had to be added.

- Revert removals of space between numerals and fractions by typogrify: in keeping with the scans.

- Revert removal of space in geometrical progression by typogrify: unfortunately let back in when typogrifying the second time.

- Tag two abbreviations in geometrical progression: forgot to do this when initially fixing the previous issue.

- [Editorial] Remove spaces from numeral: we follow 1927 everywhere else in omitting spaces in numerals containing commas, and the reason I made that decision is that 1922 usually omits the spaces too. In another commit (not otherwise relevant to the PR) I also changed 1922's periods in numerals to 1927's commas (e.g. 1922 has "8.000 fathoms"; 1927 has "8,000 fathoms"), so it's most internally consistent to just follow 1927 with respect to numerals in the absence of obvious misprintings, hence this change.

- Didn't update word count. Coincidentally after making the above changes, many of which alter the word count (restoring/removing spaces, reverting fractions), we end up with the same word count as when the ebook was originally released :) If you don't want some of the changes here, on reversion I'll update the word count as necessary.

- Add given-name semantic: tagged originally as plain `<abbr>`, but the P. represents Bloom's middle name.

### CODE REVIEW

**Comment by acabal** [comment]
I don't think typogrify adds spaces between numbers and fractions... it doesn't look right to me so I just tried it, and it doesn't. Can you remove those? You can just force-push to this PR to keep the commit history cleaner.

**Comment by erinendrei** [comment]
That's right, typogrify doesn't add spaces between numerals and fractions, it removes them, and that's what 042f2c2 reverts. For example with input "12 1/2" or "12 ½" typogrify produces "12½". (See [here](https://github.com/standardebooks/tools/blob/bae7c5b0ce938677d691df3af201eaf8e0a116ac/se/typography.py#L320) in the tools.) 042f2c2 reverts these removals of typogrify that I originally accepted, i.e. restores spaces that are in the scans and transcription.

It seems to me we have three options with the fractions:
1. Keep exactly as in the scans: 12 1/2 ([1922](https://archive.org/details/ulyssesshake1922_1large/page/624/mode/1up?q=%22million+gallons%22), [1927](https://archive.org/details/ulyssesroth1929/page/628/mode/1up?view=theater&q=%22million+gallons%22))
2. Convert fractions to unicode glyphs (or to superscript/subscript numbers and fraction slash), but don't remove spaces: 12 ½
3. Convert fractions and remove spaces:  12½

Typogrify gives result 3, and that's what appears in the ebook currently. 042f2c2 changes our approach from 3 to 2. 2 seems like a good balance to me in that it distinguishes currency notation from actual fractions and improves the appearance of fractions but still follows the scans in terms of spacing. What do you think makes the most sense?

If not 2, then I'll force-push to this PR with the required changes.

**Comment by acabal** [comment]
Let's do what typogrify does, I don't think a space makes any kind of meaningful difference. However note that £sd numbers should not be fractional glyphs, they almost always remain as-is unless they refer to an actual fraction. `/` in £sd context is a unit of account and not a fraction (unless it *is* a fraction like `1½ pence`).

**Comment by erinendrei** [comment]
OK sure, I've deleted that commit. On your second point, yes, that's exactly what led to this PR, see 32174bb and what I wrote above under "Revert conversion of currency notation to fractions by typogrify".  By "currency notation" I meant £sd notation. I'm not very familiar with it so didn't understand when first typogrifying that it had to be left alone.

**Comment by acabal** [comment]
Great, thanks!

**Comment by erinendrei** [comment]
Thanks for your patience!

**Pull request merged**
